# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/furkan/Linux_Unreal_Engine_5.8.2

TARGETS = \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	obstacleAssault-Android-DebugGame  \
	obstacleAssault-Android-Development  \
	obstacleAssault-Android-Shipping  \
	obstacleAssault-Linux-DebugGame  \
	obstacleAssault-Linux-Development  \
	obstacleAssault-Linux-Shipping  \
	obstacleAssault-LinuxArm64-DebugGame  \
	obstacleAssault-LinuxArm64-Development  \
	obstacleAssault-LinuxArm64-Shipping  \
	obstacleAssault \
	obstacleAssaultEditor-Linux-DebugGame  \
	obstacleAssaultEditor-Linux-Development  \
	obstacleAssaultEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend obstacleAssaultEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug obstacleAssaultEditor-Linux-Debug


ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

obstacleAssault-Android-DebugGame:
	 $(BUILD) obstacleAssault Android DebugGame  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssault-Android-Development:
	 $(BUILD) obstacleAssault Android Development  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssault-Android-Shipping:
	 $(BUILD) obstacleAssault Android Shipping  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssault-Linux-DebugGame:
	 $(BUILD) obstacleAssault Linux DebugGame  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssault-Linux-Development:
	 $(BUILD) obstacleAssault Linux Development  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssault-Linux-Shipping:
	 $(BUILD) obstacleAssault Linux Shipping  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssault-LinuxArm64-DebugGame:
	 $(BUILD) obstacleAssault LinuxArm64 DebugGame  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssault-LinuxArm64-Development:
	 $(BUILD) obstacleAssault LinuxArm64 Development  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssault-LinuxArm64-Shipping:
	 $(BUILD) obstacleAssault LinuxArm64 Shipping  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssault: obstacleAssault-Linux-Development

obstacleAssaultEditor-Linux-DebugGame:
	 $(BUILD) obstacleAssaultEditor Linux DebugGame  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssaultEditor-Linux-Development:
	 $(BUILD) obstacleAssaultEditor Linux Development  -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" $(ARGS)

obstacleAssaultEditor: obstacleAssaultEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/media/furkan/1TBssd/DESKTOP/Software/Cpp/unreal_Engine/obstacleAssault/obstacleAssault.uproject" -Game 

.PHONY: $(TARGETS)
